lwc_cms_shop_block:
    resource: "@LwcCmsBundle/Resources/config/routing/shop/block.yml"

lwc_cms_shop_page:
    resource: "@LwcCmsBundle/Resources/config/routing/shop/page.yml"

lwc_cms_shop_frequently_asked_question:
    resource: "@LwcCmsBundle/Resources/config/routing/shop/frequently_asked_question.yml"

lwc_cms_shop_section:
    resource: "@LwcCmsBundle/Resources/config/routing/shop/section.yml"

lwc_cms_shop_media:
    resource: "@LwcCmsBundle/Resources/config/routing/shop/media.yml"
