services:
    lwc_cms.media_provider.image:
        class: Lwc\CmsBundle\MediaProvider\GenericProvider
        arguments:
            - "@lwc_cms.media_uploader"
            - "@templating.engine.twig"
            - "@LwcCms/Shop/Media/Show/image.html.twig"
            - "media/image"
        tags:
            - { name: lwc_cms.media_provider, type: image, label: lwc_cms.ui.image_provider }

    lwc_cms.media_provider.video:
        class: Lwc\CmsBundle\MediaProvider\GenericProvider
        arguments:
            - "@lwc_cms.media_uploader"
            - "@templating.engine.twig"
            - "@LwcCms/Shop/Media/Show/video.html.twig"
            - "media/video"
        tags:
            - { name: lwc_cms.media_provider, type: video, label: lwc_cms.ui.video_provider }

    lwc_cms.media_provider.file:
        class: Lwc\CmsBundle\MediaProvider\GenericProvider
        arguments:
            - "@lwc_cms.media_uploader"
            - "@templating.engine.twig"
            - "@LwcCms/Shop/Media/Show/file.html.twig"
            - "media/file"
        tags:
            - { name: lwc_cms.media_provider, type: file, label: lwc_cms.ui.file_provider }
