imports:
    - { resource: "@LwcCmsBundle/Resources/config/resources.yml" }
    - { resource: "@LwcCmsBundle/Resources/config/grids.yml" }
    - { resource: "@LwcCmsBundle/Resources/config/services.yml" }

parameters:
    lwc_cms.uploader.filesystem: lwc_cms_media
    lwc.public_dir: '%kernel.project_dir%/public'

jms_serializer:
    metadata:
        directories:
            lwc-section:
                namespace_prefix: "Lwc\\CmsBundle"
                path: "@LwcCmsBundle/Resources/config/serializer"

knp_gaufrette:
    adapters:
        lwc_cms_media:
            local:
                directory: "%lwc.public_dir%"
                create: true
    filesystems:
        lwc_cms_media:
            adapter: "%lwc_cms.uploader.filesystem%"
