imports:
    - { resource: "@LwcCmsBundle/Resources/config/grids/admin.yml" }
    - { resource: "@LwcCmsBundle/Resources/config/grids/frontend.yml" }

sylius_grid:
    templates:
        action:
            import: "@LwcCms/Grid/Action/import.html.twig"
