lwc_cms_admin:
    resource: "@LwcCmsBundle/Resources/config/routing/admin.yml"
    prefix: /admin

lwc_cms_shop:
    resource: "@LwcCmsBundle/Resources/config/routing/shop.yml"
    prefix: /{_locale}