lwc_cms_admin:
    resource: "@LwcCmsBundle/Resources/config/routing/admin.yml"
    prefix: /admin

lwc_cms_frontend:
    resource: "@LwcCmsBundle/Resources/config/routing/frontend.yml"
    prefix: /{_locale}