lwc_cms_shop_frequently_asked_question_index:
    path: /faq
    defaults:
        _controller: lwc_cms.controller.frequently_asked_question:indexAction
        _sylius:
            template: "@LwcCmsBundle/Shop/FrequentlyAskedQuestion/index.html.twig"
            repository:
                method: findEnabledOrderedByPosition
                arguments:
                    - "expr:service('sylius.context.locale').getLocaleCode()"
