Lwc\CmsBundle\Entity\SectionTranslation:
    properties:
        name:
            - NotBlank:
                message: lwc_cms.section.name.not_blank
                groups: [Lwc]
            - Length:
                min: 2
                max: 250
                minMessage: lwc_cms.section.name.min_length
                maxMessage: lwc_cms.section.name.max_length
                groups: [Lwc]
