sylius_grid:
    grids:
        lwc_cms_admin_section:
            driver:
                name: doctrine/orm
                options:
                    class: "%lwc_cms.model.section.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                code: asc
            limits: [10, 25, 50]
            fields:
                code:
                    type: string
                    label: lwc_cms.ui.code
                    sortable: ~
                name:
                    type: string
                    label: lwc_cms.ui.name
                    sortable: translation.name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, type]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
