lwc_cms_admin_frequently_asked_question:
    resource: |
        alias: lwc_cms.frequently_asked_question
        section: admin
        templates: LwcCmsBundle:CrudUi
        redirect: update
        grid: lwc_cms_admin_frequently_asked_question
        except: ['show']
        permission: true
        vars:
            all:
                header: lwc_cms.ui.faq_header
                subheader: lwc_cms.ui.faq_subheader
                templates:
                    form: "@LwcCms/FrequentlyAskedQuestion/Crud/_form.html.twig"
            index:
                icon: help
    type: sylius.resource
