lwc_cms_admin_page:
    resource: |
        alias: lwc_cms.page
        section: admin
        templates: LwcCmsBundle:CrudUi
        redirect: update
        grid: lwc_cms_admin_page
        except: ['show']
        permission: true
        vars:
            all:
                header: lwc_cms.ui.pages_header
                subheader: lwc_cms.ui.pages_subheader
                templates:
                    form: "@LwcCms/Page/Crud/_form.html.twig"
            index:
                icon: sticky note
    type: sylius.resource

lwc_cms_admin_page_preview:
    path: /page/preview/{id}
    methods: [POST, PUT]
    defaults:
        _controller: lwc_cms.controller.page:previewAction
        _sylius:
            template: "@LwcCms/Page/preview.html.twig"
        id: null
