Lwc\CmsBundle\Entity\Block:
    type: mappedSuperclass
    table: lwc_cms_block
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            column: code
            type: string
            length: 64
            unique: true
        enabled:
            column: enabled
            type: boolean
    manyToMany:
        sections:
            targetEntity: Lwc\CmsBundle\Entity\SectionInterface
            joinTable:
                name: lwc_cms_block_sections
                joinColumns:
                    block_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    section_id:
                        referencedColumnName: id
                        onDelete: CASCADE